cask_args appdir: '/Applications'
tap 'heroku/brew'
tap 'homebrew/cask-fonts'
tap 'mongodb/brew'

#core
brew 'fish'

#command lines for osx
brew 'mmv'
brew 'rsync'
brew 'git'


#new commando lines
brew 'bat'
brew 'curlie'
brew 'dog'
brew 'duf'
brew 'dust'
brew 'jq'
brew 'lsd'
brew 'mcfly'
brew 'the_silver_searcher'
brew 'zoxide'


#development tools
brew 'asdf'
brew 'cowsay'
brew 'exercism'
cask 'dash'
cask 'font-fira-code'
brew 'gcc'
brew 'gh'
brew 'gnupg'
brew 'mongodb-database-tools'
cask 'mongodb-compass-isolated-edition'
brew 'postgresql'
cask 'r'
cask 'rstudio'
cask 'sf-symbols'
brew 'vim'
brew 'zellij'

#web developement
cask 'visual-studio-code'

#android development
cask 'android-studio'

#container tools
cask 'docker'
brew 'skaffold'

#cloud cli
brew 'awscli'
brew 'azure-cli'
cask 'google-cloud-sdk'
brew 'heroku'

#creative
cask 'adobe-creative-cloud'
cask 'scrivener'

#mac life
cask 'chromium'
cask 'discord'
cask 'disk-inventory-x'
cask 'emacs'
cask 'firefox'
cask 'google-chrome'
cask 'gpg-suite-no-mail'
cask 'kitty'
cask 'little-snitch'
brew 'mas'
cask 'microsoft-edge'
cask 'miro'
cask 'nordvpn'
cask 'rectangle'
cask 'selfcontrol'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'tunnelblick'
cask 'typora'
cask 'zoom'
brew 'zsh-completion'
brew 'zsh-syntax-highlighting'

mas '1password', id: 1333542190
mas 'excel', id: 462058435
mas 'goodnotes', id: 1444383602
mas 'keynote', id: 409183694
mas 'numbers', id: 409203825
mas 'pages', id: 409201541
mas 'spark', id: 1176895641
mas 'swiftui', id: 1485436674
mas 'word', id: 462054704

