cask_args appdir: '/Applications'
tap 'heroku/brew'
tap 'homebrew/cask-fonts'
tap 'mongodb/brew'

#core
brew 'bash'
brew 'fish'
cask 'powershell'

#command lines for osx
brew 'coreutils'
brew 'openssl'
brew 'rsync'
brew 'git'


#new commando lines
brew 'bat'
brew 'broot'
brew 'curlie'
brew 'dog'
brew 'duf'
brew 'dust'
brew 'fd'
brew 'jq'
brew 'lsd'
brew 'mcfly'
brew 'mmv'
brew 'rm-improved'
brew 'the_silver_searcher'
brew 'zoxide'

#fonts

cask 'font-3270-nerd-font'
cask 'font-caskaydia-cove-nerd-font'
cask 'font-fira-code-nerd-font'
cask 'font-hasklug-nerd-font'

#development tools
brew 'asdf'
brew 'cowsay'
brew 'exercism'
brew 'dagger'
cask 'dash'
brew 'direnv'
brew 'gcc'
brew 'gh'
brew 'gnupg'
brew 'jq'
brew 'lazydocker'
brew 'mongodb-database-tools'
cask 'mongodb-compass-isolated-edition'
brew 'neovim'
brew 'postgresql'
cask 'r'
cask 'rstudio'
cask 'sf-symbols'
cask 'svn'
brew 'vault'
brew 'yq'
brew 'zellij'

#web developement
cask 'visual-studio-code'

#android development
cask 'android-studio'

#container tools
cask 'docker'
brew 'skaffold'

#cloud cli
brew 'awscli'
brew 'azure-cli'
cask 'google-cloud-sdk'
brew 'heroku'
brew 'kube-ps1'

#creative
cask 'adobe-creative-cloud'
cask 'scrivener'

#mac life
cask '1password'
cask 'anki'
cask 'asana'
cask 'chromium'
cask 'discord'
cask 'emacs'
cask 'firefox'
cask 'google-chrome'
cask 'little-snitch'
brew 'mas'
cask 'microsoft-edge'
cask 'miro'
cask 'nordvpn'
cask 'rectangle'
cask 'selfcontrol'
cask 'slack'
cask 'tunnelblick'
cask 'typora'
cask 'zoom'
brew 'zsh-completion'
brew 'zsh-syntax-highlighting'

mas 'excel', id: 462058435
mas 'goodnotes', id: 1444383602
mas 'grandperspective', id: 1111570163
mas 'keynote', id: 409183694
mas 'numbers', id: 409203825
mas 'nebo', id: 1119601770
mas 'pages', id: 409201541
mas 'word', id: 462054704
