# Workaround for brew zsh completion

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

export EDITOR=nvim

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

setopt extendedglob

source $HOME/etc/setenv

source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
