cask_args appdir: '/Applications'
tap 'caskroom/cask'

#languages & language support
brew 'golang'
brew 'python'
brew 'python3'
brew 'rbenv'
cask 'haskell-platform'
brew 'leiningen'
cask 'mono-mdk'
cask 'java'

#web developement
brew 'nvm'
cask 'atom'
cask 'paw'

#android development
cask 'android-sdk'
cask 'android-studio'
cask 'intel-haxm'

#development tools
brew 'exercism'
brew 'the_silver_searcher'
brew 'vim'
brew 'watchman'
cask 'docker'
cask 'sublime-text'
cask 'lighttable'
cask 'macdown'
cask 'gitup'
cask 'dash'
cask 'stretchly'

#creative
cask 'adobe-creative-cloud'
cask 'sketch'
cask 'scrivener'

#mac life
cask '1password'
cask 'cathode'
cask 'chromium'
cask 'cloud'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'little-snitch'
cask 'private-internet-access'
cask 'slack'
cask 'spectacle'
mas 'wunderlist', id: 410628904
mas 'tomatoone', id: 907364780  
mas 'numbers', id: 409203825
mas 'pages', id: 409201541
mas 'keynote', id: 409183694
mas 'evernote', id: 406056744

#iOS Development
mas 'xcode', id: 497799835
