cask_args appdir: '/Applications'
tap 'heroku/brew'
tap 'caskroom/fonts'

#languages & language support
brew 'elixir'
brew 'golang'
brew 'haskell-stack'
brew 'python'
brew 'python3'
brew 'rbenv'

#web developement
brew 'nodenv'
cask 'visual-studio-code'

#android development
cask 'intel-haxm'
cask 'android-sdk'

#development tools
brew 'exercism'
cask 'dash'
cask 'docker'
cask 'font-fira-code'
brew 'git'
cask 'gitup'
brew 'heroku'
cask 'macdown'
cask 'stretchly'
cask 'tableplus'
brew 'the_silver_searcher'
brew 'vim'

#creative
cask 'adobe-creative-cloud'
cask 'scrivener'
cask 'sketch'

#mac life
cask '1password'
cask 'cathode'
cask 'chromium'
cask 'disk-inventory-x'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'little-snitch'
cask 'private-internet-access'
cask 'qlmarkdown'
cask 'slack'
cask 'spectacle'
cask 'spotify'

mas 'keynote', id: 409183694
mas 'numbers', id: 409203825
mas 'onenote', id: 784801555
mas 'pages', id: 409201541
mas 'tomatoone', id: 907364780  
mas 'trello', id: 1278508951
mas 'wunderlist', id: 410628904

#iOS Development
mas 'xcode', id: 497799835

# NOTE Java is handled by sdkman!
# this includes java dependent sdks like scala and leiningen
