#! /bin/sh
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

umask 077

source $HOME/etc/setenv

# Load up custom environment unless gnome already has.

function isMac {
	DARWIN=`uname | grep Darwin`
	return $?
}

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

SED_CMD="sed -r"

if isMac
then
	SED_CMD="sed -E"
fi

function mkcd() {
mkdir $1;cd $_
}

. ~/etc/bash/prompt



# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).

if [ -f `brew --prefix`/etc/profile.d/bash_completion.sh ]; then
    . `brew --prefix`/etc/profile.d/bash_completion.sh
fi

function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}
