#!/bin/bash

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:$PATH
export PATH=/usr/local/sbin:$PATH
export MANPATH=/usr/local/share/man:$MANPATH

export PATH=/sbin:/usr/sbin:$PATH
