#! /bin/bash


alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias editalias="nvim ~/etc/env/enabled/02-aliases"
alias env="env | sort"
alias more="less -r"
alias leetme="open https://leetcode.com/problems/random-one-question/algorithms"
alias ls="ls --color"
alias mv="mv -iv"
alias rmf='rm -f'
alias rmrm='rm -rf'
alias where="type -all"
alias xml="xmllint --format -"
alias xcrmdd='rm -v -rf $HOME/Library/Developer/Xcode/DerivedData/*'
alias zelliful="zellij attach --create beautiful"

# git commands
alias ga.="git add ."
alias gcm="git commit -m"
alias gco="git checkout"
alias gd="git diff"
alias gdc="git diff --cached"
alias gpu="git pull"
alias gp="git push"
alias gst="git status"
alias gpsup="git push -u origin $(git branch --show-current)"
alias grs="git restore -- "
alias grst="git restore --staged "

# lsd defaults
alias l="lsd -l --truncate-owner-after 3 --color always --date '+%y-%m-%d %H:%M'"
alias ll="lsd -l --color always --date '+%Y-%m-%d %H:%M:%S'"

# poetry
alias potest="poetry run pytest"

# kubernets
alias k="kubectl"