#! /bin/bash


alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias env="env | sort"
alias ls="ls --color"
alias mv="mv -iv"
alias rmf='rm -f'
alias rmrm='rm -rf'
alias where="type -all"
alias xml="xmllint --format -"
alias xcrmdd='rm -v -rf $HOME/Library/Developer/Xcode/DerivedData/*'
alias zelliful="zellij attach --create beautiful"

# temporary ohmyzsh removal coverage
alias gst="git status"
alias gco="git checkout"
alias gd="git diff"
alias gdc="git diff --cached"
alias gp="git push"

# lsd defaults
alias l="lsd -l --date '+%Y-%M-%d %H:%m:%S'"
