#!/bin/sh
export EDITOR=nvim
export MANWIDTH=80
export RSYNC_RSH=/usr/bin/ssh

# mcfly
export MCFLY_RESULTS=50

# telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT=true

# custom starship path
export STARSHIP_CONFIG=~/etc/dotfiles/config/starship.toml
