#! /bin/bash

export CLOUDSDK_PYTHON="/usr/local/opt/python@3.8/libexec/bin/python"
source `brew --prefix`/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
source `brew --prefix`/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
