#!/usr/bin/env python3
"""
Generate an extra_model_paths.yaml for ComfyUI.

Usage:
    python gen_comfyui_paths.py                # print to stdout
    python gen_comfyui_paths.py -o /path/to/extra_model_paths.yaml  # write to file

Place the output alongside ComfyUI's main.py or pass it with:
    python main.py --extra-model-paths-config <path>
"""

import argparse, logging, sys
from pathlib import Path

from core import setup_logging
from config_comfy import COMFY_MODELS_ROOT, COMFYUI_SEARCH_PATHS

log = logging.getLogger(__name__)


def generate_yaml(models_root: Path) -> str:
    lines = [
        f"# Generated by gen_comfyui_paths.py",
        f"# Points ComfyUI at: {models_root}",
        f"",
        f"ai_models:",
        f"    base_path: {models_root}",
        f"    is_default: true",
    ]

    for key, folders in COMFYUI_SEARCH_PATHS.items():
        existing = [f for f in folders if (models_root / f).exists()]
        if not existing:
            continue

        if len(existing) == 1:
            lines.append(f"    {key}: {existing[0]}")
        else:
            lines.append(f"    {key}: |")
            for f in existing:
                lines.append(f"        {f}")

    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description="Generate extra_model_paths.yaml for ComfyUI.")
    p.add_argument("-o", "--output", default=None, help="Output path (omit to print to stdout)")
    args = p.parse_args()

    setup_logging(False)
    log.debug(f"COMFY_MODELS_ROOT = {COMFY_MODELS_ROOT}")

    if not COMFY_MODELS_ROOT.exists():
        log.error(f"ComfyUI models root not found: {COMFY_MODELS_ROOT}")
        sys.exit(1)

    yaml_content = generate_yaml(COMFY_MODELS_ROOT)

    if args.output is None:
        print(yaml_content)
    else:
        out_path = Path(args.output)
        out_path.write_text(yaml_content)
        print(f"Written: {out_path}")


if __name__ == "__main__":
    main()
