
[font]
size = 14.0

[font.bold]
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[window]
option_as_alt = "Both"
startup_mode = "Maximized"
title = "playground"

[window.position]
x = 0
y = 0

[general]
import = ["themes/hyper.toml"]
